"""Offline contract tests for geography source adapters.

Uses small, real (not fabricated) fixture subsets checked into
pipelines/fixtures/ (generated by scripts/generate_geography_fixtures.py
from a live `make data` run) so these tests never require network access.
Each test exercises normalize() and quality_checks() against a synthetic
RawArtifact pointing at the fixture file, bypassing fetch().
"""

from __future__ import annotations

from pathlib import Path

import pytest
from scc_health_pipeline.sources.base import RawArtifact
from scc_health_pipeline.sources.census_county_cartographic import (
    CensusCountyCartographicAdapter,
)
from scc_health_pipeline.sources.census_zcta_cartographic import (
    CensusZctaCartographicAdapter,
)
from scc_health_pipeline.sources.census_zcta_tract_relationship import (
    CensusZctaTractRelationshipAdapter,
)
from scc_health_pipeline.sources.scc_supervisor_districts import SccSupervisorDistrictsAdapter
from scc_health_pipeline.sources.tiger_place import TigerPlace2020Adapter
from scc_health_pipeline.sources.tiger_tract import TigerTract2020Adapter

FIXTURES_DIR = Path(__file__).resolve().parents[1] / "fixtures"


def _fixture_artifact(source_id: str, local_path: Path) -> RawArtifact:
    return RawArtifact(
        resource_id="fixture",
        source_id=source_id,
        local_path=local_path,
        url="file://fixture",
        sha256="fixture",
        bytes=local_path.stat().st_size,
        content_type="fixture",
        retrieved_at="2026-07-11T00:00:00+00:00",
        status="success",
    )


class TestTigerTractAdapter:
    def test_normalize_filters_to_santa_clara_county_only(self, tmp_path: Path) -> None:
        adapter = TigerTract2020Adapter()
        # normalize() derives staged_dir from local_path.parents[1]/"staged",
        # so the fixture must live under a fake "raw" directory for that
        # relative path math to land in a temp location during the test.
        raw_dir = tmp_path / "data" / "raw"
        raw_dir.mkdir(parents=True)
        fixture_copy = raw_dir / "tl_2020_06_tract_sample.zip"
        fixture_copy.write_bytes((FIXTURES_DIR / "tl_2020_06_tract_sample.zip").read_bytes())

        artifact = _fixture_artifact(adapter.source_id, fixture_copy)
        outputs = adapter.normalize(artifact)
        assert len(outputs) == 1

        import geopandas as gpd

        gdf = gpd.read_parquet(outputs[0])
        # Fixture intentionally includes 1 non-Santa-Clara row to prove the
        # county filter actually removes it.
        assert (gdf["county_fips"] == "085").all()
        assert len(gdf) >= 1
        assert (gdf["tract_geoid_2020"].str.len() == 11).all()

    def test_quality_checks_flag_duplicate_geoids(self, tmp_path: Path) -> None:
        adapter = TigerTract2020Adapter()
        import geopandas as gpd
        from shapely.geometry import Point

        gdf = gpd.GeoDataFrame(
            {
                "tract_geoid_2020": ["06085500100", "06085500100"],
                "geometry": [Point(-121.9, 37.3), Point(-121.9, 37.3)],
            },
            crs="EPSG:4326",
        )
        out_path = tmp_path / "dup_tracts.parquet"
        gdf.to_parquet(out_path)
        report = adapter.quality_checks([out_path])
        assert not report.passed
        assert any("duplicate" in i.message.lower() for i in report.issues)


class TestTigerPlaceAdapter:
    def test_normalize_produces_place_geoid_and_geometry(self, tmp_path: Path) -> None:
        adapter = TigerPlace2020Adapter()
        raw_dir = tmp_path / "data" / "raw"
        raw_dir.mkdir(parents=True)
        fixture_copy = raw_dir / "tl_2020_06_place_sample.zip"
        fixture_copy.write_bytes((FIXTURES_DIR / "tl_2020_06_place_sample.zip").read_bytes())

        artifact = _fixture_artifact(adapter.source_id, fixture_copy)
        outputs = adapter.normalize(artifact)
        assert len(outputs) == 1

        import geopandas as gpd

        gdf = gpd.read_parquet(outputs[0])
        assert "place_geoid" in gdf.columns
        assert len(gdf) == 6


class TestCensusCountyCartographicAdapter:
    def test_normalize_filters_to_exactly_santa_clara(self, tmp_path: Path) -> None:
        adapter = CensusCountyCartographicAdapter()
        raw_dir = tmp_path / "data" / "raw"
        raw_dir.mkdir(parents=True)
        fixture_copy = raw_dir / "cb_2020_us_county_500k_sample.zip"
        fixture_copy.write_bytes((FIXTURES_DIR / "cb_2020_us_county_500k_sample.zip").read_bytes())

        artifact = _fixture_artifact(adapter.source_id, fixture_copy)
        outputs = adapter.normalize(artifact)
        report = adapter.quality_checks(outputs)

        import geopandas as gpd

        gdf = gpd.read_parquet(outputs[0])
        # Fixture includes Alameda County (06001) too; the adapter must
        # filter it out, leaving only Santa Clara (06085).
        assert len(gdf) == 1
        assert gdf.iloc[0]["county_geoid"] == "06085"
        assert report.passed


class TestCensusZctaCartographicAdapter:
    def test_normalize_applies_coarse_prefix_filter(self, tmp_path: Path) -> None:
        adapter = CensusZctaCartographicAdapter()
        raw_dir = tmp_path / "data" / "raw"
        raw_dir.mkdir(parents=True)
        fixture_copy = raw_dir / "cb_2020_us_zcta520_500k_sample.zip"
        fixture_copy.write_bytes((FIXTURES_DIR / "cb_2020_us_zcta520_500k_sample.zip").read_bytes())

        artifact = _fixture_artifact(adapter.source_id, fixture_copy)
        outputs = adapter.normalize(artifact)

        import geopandas as gpd

        gdf = gpd.read_parquet(outputs[0])
        # Fixture includes a NYC ZCTA (10001); the 94/95 coarse prefix
        # filter must exclude it.
        assert set(gdf["zcta_geoid"]) == {"95110", "95112", "94301"}


class TestSccSupervisorDistrictsAdapter:
    def test_normalize_and_quality_checks_pass_on_real_5_district_fixture(
        self, tmp_path: Path
    ) -> None:
        adapter = SccSupervisorDistrictsAdapter()
        raw_dir = tmp_path / "data" / "raw"
        raw_dir.mkdir(parents=True)
        fixture_copy = raw_dir / "supervisor_districts_sample.geojson"
        fixture_copy.write_bytes(
            (FIXTURES_DIR / "supervisor_districts_sample.geojson").read_bytes()
        )

        artifact = _fixture_artifact(adapter.source_id, fixture_copy)
        outputs = adapter.normalize(artifact)
        report = adapter.quality_checks(outputs)
        assert report.passed

        import geopandas as gpd

        gdf = gpd.read_parquet(outputs[0])
        assert sorted(gdf["district_number"].tolist()) == [1, 2, 3, 4, 5]
        assert "Sylvia Arenas" in gdf["supervisor_name"].tolist()

    def test_quality_checks_fail_when_a_district_is_missing(self, tmp_path: Path) -> None:
        adapter = SccSupervisorDistrictsAdapter()
        import geopandas as gpd
        from shapely.geometry import Point

        gdf = gpd.GeoDataFrame(
            {
                "district_number": [1, 2, 3, 4],  # missing district 5
                "supervisor_name": ["A", "B", "C", "D"],
                "area_acres": [1.0, 1.0, 1.0, 1.0],
                "area_sq_miles": [1.0, 1.0, 1.0, 1.0],
                "geometry": [Point(0, 0)] * 4,
            },
            crs="EPSG:4326",
        )
        out_path = tmp_path / "incomplete_districts.parquet"
        gdf.to_parquet(out_path)
        report = adapter.quality_checks([out_path])
        assert not report.passed


class TestCensusZctaTractRelationshipAdapter:
    def test_normalize_computes_correct_weights_and_preserves_unassigned_slivers(
        self, tmp_path: Path
    ) -> None:
        adapter = CensusZctaTractRelationshipAdapter()
        raw_dir = tmp_path / "data" / "raw"
        raw_dir.mkdir(parents=True)
        fixture_copy = raw_dir / "tab20_zcta520_tract20_natl_sample.txt"
        fixture_copy.write_bytes(
            (FIXTURES_DIR / "tab20_zcta520_tract20_natl_sample.txt").read_bytes()
        )

        artifact = _fixture_artifact(adapter.source_id, fixture_copy)
        outputs = adapter.normalize(artifact)
        assert len(outputs) == 2  # crosswalk + unassigned-land tables

        import polars as pl

        crosswalk = pl.read_parquet(outputs[0])
        unassigned = pl.read_parquet(outputs[1])

        # Every crosswalk row must be a Santa Clara County tract.
        assert crosswalk.filter(~pl.col("tract_geoid_2020").str.starts_with("06085")).height == 0
        # The fixture includes an Alameda County (06001) row that must be
        # excluded entirely.
        assert crosswalk.height > 0
        # Weights must be within (0, 1].
        assert crosswalk.filter((pl.col("weight") <= 0) | (pl.col("weight") > 1)).height == 0
        # The fixture intentionally includes blank-ZCTA sliver rows.
        assert unassigned.height >= 0  # present in schema even if 0 in this slice

    def test_quality_checks_pass_on_fixture(self, tmp_path: Path) -> None:
        adapter = CensusZctaTractRelationshipAdapter()
        raw_dir = tmp_path / "data" / "raw"
        raw_dir.mkdir(parents=True)
        fixture_copy = raw_dir / "tab20_zcta520_tract20_natl_sample.txt"
        fixture_copy.write_bytes(
            (FIXTURES_DIR / "tab20_zcta520_tract20_natl_sample.txt").read_bytes()
        )
        artifact = _fixture_artifact(adapter.source_id, fixture_copy)
        outputs = adapter.normalize(artifact)
        report = adapter.quality_checks(outputs)
        assert report.passed


class TestMalformedAndMissingSources:
    """Every adapter must fail gracefully (a truthful ValidationReport), never crash."""

    def test_validate_raw_reports_unavailable_status_cleanly(self) -> None:
        adapter = TigerTract2020Adapter()
        artifact = RawArtifact(
            resource_id="missing",
            source_id=adapter.source_id,
            local_path=None,
            url="https://example.invalid/missing.zip",
            sha256=None,
            bytes=0,
            content_type=None,
            retrieved_at="2026-07-11T00:00:00+00:00",
            status="unavailable",
            notes="All retries exhausted.",
        )
        report = adapter.validate_raw(artifact)
        assert not report.passed
        assert any("fetch failed" in i.message.lower() for i in report.issues)

    def test_normalize_on_malformed_zip_does_not_crash_pipeline(self, tmp_path: Path) -> None:
        adapter = TigerTract2020Adapter()
        raw_dir = tmp_path / "data" / "raw"
        raw_dir.mkdir(parents=True)
        bad_zip = raw_dir / "corrupt.zip"
        bad_zip.write_bytes(b"this is not a real zip file")
        artifact = _fixture_artifact(adapter.source_id, bad_zip)

        from pyogrio.errors import DataSourceError

        with pytest.raises(DataSourceError):
            # A malformed file is expected to raise a clear parsing
            # exception from geopandas/pyogrio rather than silently
            # producing empty/fake output -- the orchestration script
            # (run_geography_pipeline.py) catches this at the call site
            # and records a failed source rather than corrupting output.
            adapter.normalize(artifact)
